### ISSUE TITLE
Can I build only the C library with no Rust or cargo involved?

### ISSUE THREAD

**Issue by mavavilj** [Sytronik/pyin-rs#2]
Can I build only the C library with no Rust or cargo involved?

**Comment by Sytronik** [comment]
You need Rust build system (rustc at least) to compile this project because this project was fully written in Rust.
But after you build once, you can get the C shared object and header file.
You can use them.

**Comment by Sytronik** [comment]
You can check how your C program includes this library in `compile_test.sh`

**Comment by mavavilj** [comment]
Okay, thank you.

Any tips for how to get a shared library for Android and possibly iOS?

I already explored cargo-ndk with some confusion:

https://github.com/bbqsrc/cargo-ndk/issues/124

**Comment by mavavilj** [comment]
If the above are not possible, then I am interested in doing a pure C port.

**Comment by Sytronik** [comment]
I'm sorry, I have a poor knowledge about cross-compile with Cargo.

**Comment by mavavilj** [comment]
Okay, then it's a bit sad, because a permissibly licensed pYIN would be useful for other platforms.
